// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskSmart.Server.DataAccess.DBContext;

#nullable disable

namespace TestTaskSmart.Server.Migrations
{
    [DbContext(typeof(TestAppContext))]
    [Migration("20240714231127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveRequestId")
                        .IsUnique();

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeoplePartnerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SubdivisionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeoplePartnerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("SubdivisionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0,
                            FullName = "Admin Admin",
                            Login = "admin",
                            Password = "admin",
                            PositionId = 1,
                            Status = true,
                            SubdivisionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 0,
                            FullName = "Alice HR",
                            Login = "hr1",
                            Password = "hr1",
                            PositionId = 2,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0,
                            FullName = "Bob HR",
                            Login = "hr2",
                            Password = "hr2",
                            PositionId = 2,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 0,
                            FullName = "Charlie PM",
                            Login = "pm1",
                            Password = "pm1",
                            PositionId = 3,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Balance = 0,
                            FullName = "David PM",
                            Login = "pm2",
                            Password = "pm2",
                            PositionId = 3,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 6,
                            Balance = 5,
                            FullName = "Emma Emp",
                            Login = "emp1",
                            Password = "emp1",
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Balance = 5,
                            FullName = "Liam Emp",
                            Login = "emp2",
                            Password = "emp2",
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Balance = 21,
                            FullName = "Jazmyn Bergstrom",
                            Login = "Joe.Altenwerth33",
                            Password = "Rwnrp8rCto",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Balance = 21,
                            FullName = "Trudie Bashirian",
                            Login = "Rahul8",
                            Password = "tKoJguhGRH",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 10,
                            Balance = 9,
                            FullName = "Vladimir Jacobi",
                            Login = "Ned_Moore65",
                            Password = "2u55jsmXvJ",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 11,
                            Balance = 5,
                            FullName = "Desiree Wolf",
                            Login = "Ruthe_Lang",
                            Password = "UzwfltqNm4",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 12,
                            Balance = 16,
                            FullName = "Florencio Brown",
                            Login = "Major_Ondricka5",
                            Password = "Gqwszre_3d",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 13,
                            Balance = 14,
                            FullName = "Bernita Jacobs",
                            Login = "Rosario.Schiller",
                            Password = "c9I3uSJIoN",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 14,
                            Balance = 16,
                            FullName = "Frederic Rolfson",
                            Login = "Jo.Muller26",
                            Password = "oiiDtgtKcV",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 15,
                            Balance = 17,
                            FullName = "Elody D'Amore",
                            Login = "Juwan.Dibbert",
                            Password = "MsQHevYp2o",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 16,
                            Balance = 11,
                            FullName = "Claudine Schmidt",
                            Login = "Giovani_Vandervort41",
                            Password = "oOQXOEc5D9",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 17,
                            Balance = 25,
                            FullName = "Alison Bayer",
                            Login = "Myrtie.Zboncak",
                            Password = "72h0Gydnkw",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 18,
                            Balance = 21,
                            FullName = "Benton Schinner",
                            Login = "Winona_Kohler42",
                            Password = "jpxmByZ4un",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 19,
                            Balance = 7,
                            FullName = "Keon Dare",
                            Login = "Floy_Barrows",
                            Password = "J2qW3Q7bzs",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 20,
                            Balance = 4,
                            FullName = "Casper Kemmer",
                            Login = "Jean_Koss",
                            Password = "AH68qiqVQX",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 21,
                            Balance = 5,
                            FullName = "Name Wuckert",
                            Login = "Rodolfo.Windler16",
                            Password = "O8nx9Wrsq3",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 22,
                            Balance = 2,
                            FullName = "Maximo Rogahn",
                            Login = "Leanna_Bartoletti",
                            Password = "HyzHvDYi7Z",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 23,
                            Balance = 16,
                            FullName = "Lelah Fritsch",
                            Login = "Scarlett.Kris96",
                            Password = "lSqj7PFAI4",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 24,
                            Balance = 21,
                            FullName = "Bernadine Schamberger",
                            Login = "Emelie_Jast73",
                            Password = "QwXuuh7hkl",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 25,
                            Balance = 14,
                            FullName = "Reece D'Amore",
                            Login = "Carmela41",
                            Password = "soCQ50CfZI",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 26,
                            Balance = 12,
                            FullName = "Bella Bradtke",
                            Login = "Giuseppe2",
                            Password = "MRhrXsOOlq",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 27,
                            Balance = 16,
                            FullName = "Cade Harvey",
                            Login = "Kyra.Boehm",
                            Password = "73VO17ln25",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 28,
                            Balance = 4,
                            FullName = "Sigrid Nicolas",
                            Login = "Carole64",
                            Password = "uBsVq4AjG8",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 29,
                            Balance = 17,
                            FullName = "Reinhold Lemke",
                            Login = "Tressie48",
                            Password = "AstlNUOrQH",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 30,
                            Balance = 28,
                            FullName = "Jedediah Morissette",
                            Login = "Emilio.Cummerata27",
                            Password = "V1OX_7BIC2",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 31,
                            Balance = 18,
                            FullName = "Arno Quigley",
                            Login = "Guillermo94",
                            Password = "s7pLPsdOfK",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 32,
                            Balance = 27,
                            FullName = "Geovanny Schneider",
                            Login = "Eileen_Murphy47",
                            Password = "DGw1Bm1sL3",
                            PeoplePartnerId = 2,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 2
                        },
                        new
                        {
                            Id = 33,
                            Balance = 4,
                            FullName = "Colten Batz",
                            Login = "Lilyan.Lowe15",
                            Password = "ki38Kl3h6y",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 34,
                            Balance = 13,
                            FullName = "Allen Weber",
                            Login = "Richard_Stracke8",
                            Password = "JAqMBzT2T6",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 35,
                            Balance = 8,
                            FullName = "Haleigh Dickinson",
                            Login = "Ethyl.Wilkinson",
                            Password = "Yp7qo3P2A9",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 36,
                            Balance = 6,
                            FullName = "Garfield Gislason",
                            Login = "Alexie46",
                            Password = "bRXLcj49GV",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 37,
                            Balance = 5,
                            FullName = "Audreanne Fritsch",
                            Login = "Judah_Dickens",
                            Password = "0dN9LvoPQa",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 38,
                            Balance = 22,
                            FullName = "Annie O'Connell",
                            Login = "Kimberly54",
                            Password = "PDvK0X5ZAC",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 39,
                            Balance = 11,
                            FullName = "Jan Tromp",
                            Login = "Bailee.Bogan90",
                            Password = "yy34MoS1b1",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 40,
                            Balance = 2,
                            FullName = "Israel Kohler",
                            Login = "Maiya.Pagac",
                            Password = "wLVry1Ncjm",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 41,
                            Balance = 25,
                            FullName = "Delphia Bartell",
                            Login = "Maxwell8",
                            Password = "uSqvp300sy",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 42,
                            Balance = 5,
                            FullName = "Madyson Daniel",
                            Login = "Russell.Berge55",
                            Password = "y2qzKKTtPe",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 43,
                            Balance = 22,
                            FullName = "Pasquale O'Kon",
                            Login = "Percy.Hayes11",
                            Password = "YpkUEuJsvX",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 44,
                            Balance = 8,
                            FullName = "Rowena Jakubowski",
                            Login = "Kathryne92",
                            Password = "MsSQIY4SL4",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 45,
                            Balance = 17,
                            FullName = "Modesta Frami",
                            Login = "Paris.Rau",
                            Password = "wI_Jr6LPga",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 46,
                            Balance = 9,
                            FullName = "Pink Walter",
                            Login = "Eriberto92",
                            Password = "43Lr3d2Huk",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 47,
                            Balance = 8,
                            FullName = "Hassie Fay",
                            Login = "Emmanuelle_Hauck55",
                            Password = "WfM65CbrGx",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 48,
                            Balance = 3,
                            FullName = "Keyon Hayes",
                            Login = "Harvey.Buckridge31",
                            Password = "8gJzNdXOxD",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 49,
                            Balance = 18,
                            FullName = "Rebecca Fahey",
                            Login = "Olga42",
                            Password = "laOc5Dj8IZ",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 50,
                            Balance = 6,
                            FullName = "Felicia Collier",
                            Login = "Isac_Witting10",
                            Password = "pdk1sOLafI",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 51,
                            Balance = 25,
                            FullName = "Berry Volkman",
                            Login = "Sophie.Schultz",
                            Password = "VqfgpWTEjP",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 52,
                            Balance = 29,
                            FullName = "Theo Koelpin",
                            Login = "Rylan_Gleason",
                            Password = "x4kGFiP8QH",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 53,
                            Balance = 30,
                            FullName = "Ford Padberg",
                            Login = "Chauncey_Turner",
                            Password = "C0ewLNm0iv",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 54,
                            Balance = 7,
                            FullName = "Carmen Klocko",
                            Login = "Jerry39",
                            Password = "MavblyI0qf",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 55,
                            Balance = 21,
                            FullName = "Kevon Huels",
                            Login = "Mckenna.VonRueden",
                            Password = "kdnyNPVQtE",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 56,
                            Balance = 20,
                            FullName = "Lisa Lesch",
                            Login = "Wava.Purdy",
                            Password = "EP2uXwL600",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = false,
                            SubdivisionId = 3
                        },
                        new
                        {
                            Id = 57,
                            Balance = 12,
                            FullName = "Reinhold Weimann",
                            Login = "Stan26",
                            Password = "gZJVwBVEVK",
                            PeoplePartnerId = 3,
                            PositionId = 4,
                            Status = true,
                            SubdivisionId = 3
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.EmployeesProjects", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeesProjects");

                    b.HasData(
                        new
                        {
                            EmployeeId = 14,
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 25,
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 13,
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 11,
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 31,
                            ProjectId = 3
                        },
                        new
                        {
                            EmployeeId = 33,
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsenceReason")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbsenceReason = 0,
                            Comment = "",
                            EmployeeId = 9,
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6185),
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6133),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AbsenceReason = 1,
                            Comment = "",
                            EmployeeId = 10,
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6193),
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6191),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AbsenceReason = 2,
                            Comment = "",
                            EmployeeId = 14,
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6197),
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6195),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AbsenceReason = 3,
                            Comment = "",
                            EmployeeId = 32,
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6200),
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6199),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AbsenceReason = 4,
                            Comment = "",
                            EmployeeId = 31,
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6203),
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6202),
                            Status = 1
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PM"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectManagerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "",
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6280),
                            ProjectManagerId = 4,
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6278),
                            Status = true,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Comment = "",
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6285),
                            ProjectManagerId = 4,
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6284),
                            Status = true,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "",
                            EndDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6289),
                            ProjectManagerId = 5,
                            StartDate = new DateTime(2024, 7, 15, 2, 11, 20, 989, DateTimeKind.Local).AddTicks(6288),
                            Status = true,
                            Type = 1
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subdivisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Subdivision1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Subdivision2"
                        });
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.ApprovalRequest", b =>
                {
                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.LeaveRequest", "LeaveRequest")
                        .WithOne("ApprovalRequest")
                        .HasForeignKey("TestTaskSmart.Server.DataAccess.Models.ApprovalRequest", "LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Employee", b =>
                {
                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Employee", "PeoplePartner")
                        .WithMany()
                        .HasForeignKey("PeoplePartnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Subdivision", "Subdivision")
                        .WithMany()
                        .HasForeignKey("SubdivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeoplePartner");

                    b.Navigation("Position");

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.EmployeesProjects", b =>
                {
                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.LeaveRequest", b =>
                {
                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.Project", b =>
                {
                    b.HasOne("TestTaskSmart.Server.DataAccess.Models.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("TestTaskSmart.Server.DataAccess.Models.LeaveRequest", b =>
                {
                    b.Navigation("ApprovalRequest")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
